spring:
  application.name: integrating-spring-boot-with-postgres
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database_name
    username: postgres
    password: postgres
