spring:
  application.name: integrating-spring-boot-with-postgres
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database_name
    username: postgres
    password: postgres
